name: cmo
description: Supply chain integrity.

publish_to: "none"

version: 1.2.0+18

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  after_layout: ^1.2.0
  android_id: ^0.1.3+1
  another_flushbar: ^1.12.29
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.2
  cookie_jar: ^3.0.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^8.1.0
  dio: ^5.0.3
  easy_localization: ^3.0.1
  envied: ^0.3.0
  equatable: ^2.0.5
  ficonsax: ^0.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_form_builder: ^7.8.0
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.1
  form_builder_validators: ^8.5.0
  freezed_annotation: null
  geocoding: ^2.1.0
  get_it: ^7.2.0
  google_maps_flutter: ^2.2.5
  hydrated_bloc: ^9.1.0
  image_cropper: ^3.0.2
  image_picker: ^0.8.7
  isar: 3.0.5
  isar_flutter_libs: 3.0.5
  json_annotation: ^4.7.0
  logger: ^1.3.0
  path_provider: ^2.0.13
  pretty_dio_logger: ^1.3.1
  sealed_flutter_bloc: ^8.0.1
  sembast: ^3.4.1+1
  sembast_sqflite: ^2.1.0+1
  sqflite: ^2.2.6
  syncfusion_flutter_signaturepad: ^21.1.41
  url_launcher: ^6.1.9
  very_good_analysis: ^4.0.0+1
  hand_signature: ^3.0.1
  maps_toolkit: ^2.0.1
  intl: ^0.17.0
  shared_preferences: ^2.1.1
  geolocator: ^9.0.2
  map_autocomplete_field: ^0.0.2
  flutter_html: ^3.0.0-beta.2
  tuple: ^2.0.2
  easy_image_viewer: ^1.2.1
  app_settings: ^5.0.0
  share_plus: ^7.1.0
  flutter_slidable: ^3.0.0
  camera: ^0.10.5+5
  package_info_plus: ^4.2.0

dev_dependencies:
  build_runner: null
  envied_generator: ^0.3.0
  flutter_gen_runner: null

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: null
  import_sorter: ^4.6.0
  isar_generator: 3.0.5
  json_serializable: 6.6.1

import_sorter:
  emojis: false
  comments: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/l10n/

  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: fonts/NotoSans-Italic.ttf
          style: italic

flutter_gen:
  integrations:
    flutter_svg: true

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  l10n: flutter pub run easy_localization:generate -S assets/l10n -O lib/l10n -f
    keys -o locale_keys.g.dart
