import 'package:freezed_annotation/freezed_annotation.dart';

part 'farmer_sync_summary_state.freezed.dart';

@freezed
class FarmerSyncSummaryState with _$FarmerSyncSummaryState {
  const factory FarmerSyncSummaryState({
    @Default(false) bool isLoading,
    @Default(false) bool isSyncing,
    String? syncMessage,
    FarmerSyncSummaryModel? data,
    int? userId,
    int? userDeviceId,
    int? groupSchemeId,
    String? farmId,
    int? rmuId,
  }) = _FarmerSyncSummaryState;
}

@freezed
class FarmerSyncSummaryModel with _$FarmerSyncSummaryModel {
  const factory FarmerSyncSummaryModel({
    int? workersUnsynced,
    int? workersTotal,
    int? accidentAndIncidentUnsynced,
    int? accidentAndIncidentTotal,
    int? accidentAndIncidentPropertyDamagedUnsynced,
    int? accidentAndIncidentPropertyDamagedTotal,
    int? asiUnsynced,
    int? asiTotal,
    int? asiPhotosUnsynced,
    int? asiPhotosTotal,
    int? biologicalControlAgentsUnsynced,
    int? biologicalControlAgentsTotal,
    int? chemicalsUnsynced,
    int? chemicalsTotal,
    int? disciplinariesUnsynced,
    int? disciplinariesTotal,
    int? stakeholderComplaintsUnsynced,
    int? stakeholderComplaintsTotal,
    int? employeeGrievancesUnsynced,
    int? employeeGrievancesTotal,
    int? fireUnsynced,
    int? fireTotal,
    int? petsAndDiseaseUnsyced,
    int? petsAndDiseaseTotal,
    int? petsAndDiseaseTreatmentMethodsUnsyced,
    int? petsAndDiseaseTreatmentMethodsTotal,
    int? rteSpeciesRegistersUnsynced,
    int? rteSpeciesRegistersTotal,
    int? rteSpeciesRegistersPhotosUnsynced,
    int? rteSpeciesRegistersPhotosTotal,
    int? trainingUnsynced,
    int? trainingTotal,
    int? annualProductionUnsynced,
    int? annualProductionTotal,
    int? annualBudgetTransactionsUnsynced,
    int? annualBudgetTransactionsTotal,
    int? annualBudgetsProductionUnsynced,
    int? annualBudgetsProductionTotal,
    int? campsUnsynced,
    int? campsTotal,
    int? schedulerUnsynced,
    int? upcomingEvent,
    int? biologicalControlAgentTypes,
    int? annualFarmBudgetTransactionCategory,
    int? asiType,
    int? chemicalApplicationMethods,
    int? chemicalTypes,
    int? countries,
    int? fireCause,
    int? gender,
    int? grievanceIssue,
    int? groupScheme,
    int? disciplinariesIssues,
    int? jobDescription,
    int? monitoringRequirement,
    int? natureOfInjury,
    int? petsAndDiseaseType,
    int? petsAndDiseaseTypeTreatmentMethod,
    int? propertyDamaged,
    int? rejectReasons,
    int? scheduleActivity,
    int? speciesRange,
    int? speciesTypes,
    int? trainingType,
    int? treatmentMethod,
    int? stakeholderUnsynced,
    int? customaryUseRights,
    int? farmStakeHolders,
    int? groupSchemeStakeholders,
    int? socialUpliftments,
    int? specialSites,
    int? stakeholderTypes,
  }) = _FarmerSyncSummaryModel;
}
